title: "Fahrin Andiwijaya"
description: "PM&R | rehab, EMG/NCV, stats"
lang: en
permalink: /:title/

# Pull the theme directly from GitHub
remote_theme: sharadcodes/jekyll-theme-dark-reader
plugins:
  - jekyll-remote-theme
  - jekyll-feed   # optional

# Dark Reader theme basics
author: "Fahrin Andiwijaya"
